### PR TITLE
I have added unit tests for signup component. I have increased coverage from 30% to 70%. Please, review this PR. Regards.

### PR DESCRIPTION
**Pull request by AlexandreInsua**
I have added unit tests for signup component. I have increased coverage from 30% to 70%. Please, review this PR. Regards.

### CODE REVIEW

**Comment by shubhamjsx** [comment]
@AlexandreInsua Can you fix the lint errors? Build is failing because of that.

**Comment by shubhamjsx** [comment]
@AlexandreInsua , Please run `ng lint` to see the errors in local . you can download the ESLint VSCode extention, will come in handy.

**Comment by AlexandreInsua** [comment]
Hi, @shubham-kumar10 , PR is still blocked due there are conflicts in app.component.spec.ts, but I haven't changed it. I don't undertand what's happening. Have you any idea?

**Comment by AlexandreInsua** [comment]
Finally, it is done.

**Review by shubhamjsx — APPROVED** [review]

**Comment by shubhamjsx** [comment]
> Finally, it is done.

Thank you, merged!

**Pull request merged**
